#! /bin/bash

set -euo pipefail

cd $(dirname ${BASH_SOURCE[0]})

. ../functions.sh

ssh -V

DIR=~/.ssh
mkdir -p ${DIR}
SSH_CONFIG=config.default
if [[ $(hostname) == *jorson* ]]; then
    SSH_CONFIG=config.work
fi
rm -f ${DIR}/config
cp -vf ~/git.sr.ht/jamesaorson/bootstrap/ssh/${SSH_CONFIG} ${DIR}/config
