#! /bin/bash

set -euo pipefail

cd $(dirname ${BASH_SOURCE[0]})

. ../functions.sh

ssh -V

DIR=~/.ssh
mkdir -p ${DIR}
SSH_CONFIG=config.default
if [[ $(hostname) == *jorson* ]]; then
    SSH_CONFIG=config.work
fi
rm -f ${DIR}/config
ln -s -f $(pwd)/${SSH_CONFIG} ${DIR}/config

