[env]
TERM = "xterm-256color"

# [shell]
# program = "tmux"
# args = [
#     "new-session",
#     "-A",
#     "-D",
#     "-s",
#     "main",
# ]

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 22.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000

[window]
dynamic_title = true
startup_mode = "Maximized"
title = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#c7c7c7"
text = "#feffff"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.bright]
black = "#2b2b2b"
blue = "#56bcf0"
cyan = "#8ef9fd"
green = "#77f54a"
magenta = "#b93ec1"
red = "#ef766d"
white = "#feffff"
yellow = "#fefb7e"

[colors.normal]
black = "#2b2b2b"
blue = "#6a71f6"
cyan = "#53c2c5"
green = "#77d049"
magenta = "#b93ec1"
red = "#ea4127"
white = "#c7c7c7"
yellow = "#efec4e"

[colors.primary]
background = "#181818"
bright_foreground = "#c7c7c7"
dim_foreground = "#c7c7c7"
foreground = "#c7c7c7"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

#[colors.search.footer_bar]
#background = "#A6ADC8"
#foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

