#!/usr/bin/env bash
# PreToolUse hook: block commits, PRs, and issues that carry AI attribution.
set -euo pipefail

readonly PATTERN='generated (by|with) \[?claude|co-authored-by:.*(claude|anthropic)'

readonly cmd=$(jq -r '.tool_input.command // empty')
grep -Eq '(git (commit|tag)|gh (pr|issue|release|api))' <<<"$cmd" || exit 0

# Body text may live in a file (--body-file, -F, --file).
files=$(grep -Eo '(--body-file|--file|-F)[ =]+[^ ]+' <<<"$cmd" | sed -E 's/^[^ =]+[ =]+//; s/^["'\'']//; s/["'\'']$//' || true)
text=$cmd
for f in $files; do
    [[ -f $f ]] && text+=$'\n'$(cat "$f")
done

if grep -Eiq "$PATTERN" <<<"$text"; then
    echo "Blocked: remove the AI attribution line (\"Generated by/with Claude\", Co-Authored-By: Claude) and retry." >&2
    exit 2
fi
