#! /bin/bash

set -eo pipefail

cd $(dirname ${BASH_SOURCE[0]})

if ! command -v curl >> /dev/null; then
    # NOTE: Directly call, bypassing setup to avoid accidental recursion
    # NOTE: curl is bundled with MacOS, so this only affects linux installs, so we want to avoid the recursion
    ../curl/setup curl
fi

export GOVERSION="${GOVERSION:-1.21.5}"
export GOPATH="${GOPATH:-${HOME}/.local/go/path}"
export GOROOT="${GOROOT:-${HOME}/.local/go/root/${GOVERSION}}"
mkdir -p ${GOPATH}

set -u

if [[ -d ${GOROOT} ]]; then
    echo "Go ${GOVERSION} is already installed"
    exit 0
fi

mkdir -p ${GOROOT}

TARBALL="go${GOVERSION}.linux-amd64.tar.gz"
curl -fsSL -O "https://go.dev/dl/${TARBALL}"
mkdir -p ${GOROOT}
tar -C "${GOROOT}" -xzf ./${TARBALL}
rm -f ./${TARBALL}

${GOROOT}/go/bin/go version

rm -f ${HOME}/.local/bin/go
ln -s ${GOROOT}/go/bin/go ${HOME}/.local/bin/go

