#! /bin/bash

set -eo pipefail

cd $(dirname ${BASH_SOURCE[0]})

if ! command -v curl >> /dev/null; then
    # NOTE: Directly call, bypassing setup to avoid accidental recursion
    # NOTE: curl is bundled with MacOS, so this only affects linux installs, so we want to avoid the recursion
    ../curl/setup curl
fi

LOCAL_DIRECTORY="${HOME}/.local"
GO_INSTALL_DIRECTORY=${LOCAL_DIRECTORY}/go
GO_VERSION="1.23.2"

GO="${GO_INSTALL_DIRECTORY}/bin/go"
if [[ -f ${GO} ]]; then
    echo "Go ${GO_VERSION} is already installed"
    exit 0
fi

UNAME_S=$(uname -s | tr '[:upper:]' '[:lower:]')
UNAME_M=$(uname -m)
if [[ ${UNAME_M} == aarch64 ]]; then
	ARCH=arm64
else
	ARCH=${UNAME_M}
fi

mkdir -p ${LOCAL_DIRECTORY}
rm -rf ${GO_INSTALL_DIRECTORY}
curl -L "https://go.dev/dl/go${GO_VERSION}.${UNAME_S}-${ARCH}.tar.gz" | tar -C ${LOCAL_DIRECTORY} -xz

