#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

. ../functions.sh

PLATFORM=$(uname -s)
case ${PLATFORM} in
    Linux*)
        bootstrap_install git
        ;;
    *)
        ;;
esac

git --version

DIR=${HOME}/.local/git
TEMPLATE_DIR=${DIR}/template

mkdir -p ${DIR}

rm -f ${HOME}/.gitconfig

set +u
GITCONFIG=gitconfig.default
if [[ -n "${IS_PURE}" ]]; then
    GITCONFIG=gitconfig.work
fi
set -u
ln -s -f $(pwd)/${GITCONFIG} ~/.gitconfig
rm -f ${TEMPLATE_DIR}
ln -s -f $(pwd)/template ${TEMPLATE_DIR}

GNUPG_DIR=${HOME}/.gnupg
mkdir -p -m 700 ${GNUPG_DIR}
ln -s -f $(pwd)/gpg-agent.conf ${GNUPG_DIR}/gpg-agent.conf
if command -v gpgconf >> /dev/null; then
    gpgconf --reload gpg-agent
fi
