#! /bin/bash

cd $(dirname ${BASH_SOURCE[0]})

. ../functions.sh

# Vim setup
ln -s -f $(pwd)/.vimrc ${HOME}/.vimrc

# Neovim setup

PLATFORM="$(uname -a)"
case ${PLATFORM} in
    Linux*)
 	if [ $(echo ${PLATFORM} | grep -ic "Linux pi") -gt 0 ]; then
	    sudo apt-get install \
                python3-launchpadlib
	fi
        if sudo -v; then
            sudo add-apt-repository -y ppa:neovim-ppa/unstable
        fi
		PACKAGE=guix.scm
		rm -f ${PACKAGE}
		curl -s https://codeberg.org/rgherdt/scheme-lsp-server/raw/commit/428f2e8dbe37eff8c769f40ede8a80e99417e28e/guix.scm > ${PACKAGE}
		guix package -f ${PACKAGE}
        ;;
    Darwin*)
        ;;
    *)          echo "UNKNOWN:${unameOut}"; exit 1;;
esac

bootstrap_install neovim
nvim -V1 -v

CONFIG_DIR=${HOME}/.config
mkdir -p ${CONFIG_DIR}
rm -f ${HOME}/.config/nvim
ln -s -f $(pwd)/config ${HOME}/.config/nvim

# Language Servers


## Scheme Language Server - https://github.com/ufo5260987423/scheme-langserver


