#! /bin/bash

cd $(dirname ${BASH_SOURCE[0]})

. ../functions.sh

# Vim setup
ln -s -f $(pwd)/.vimrc ${HOME}/.vimrc

# Neovim setup

PLATFORM="$(uname -a)"
case ${PLATFORM} in
    Linux*)
		    if [[ ${PLATFORM} == "Linux pi"* ]]; then
				  sudo apt install ninja-build gettext cmake unzip curl
				  mkdir -p ${HOME}/.local/src
					sudo rm -rf ${HOME}/.local/src/neovim/{build,.deps}
				  BRANCH=v0.10.2 bootstrap_clone https://github.com/neovim/neovim ${HOME}/.local/src/neovim
				  pushd ${HOME}/.local/src/neovim
					sudo make CMAKE_BUILD_TYPE=Release
					cd build && sudo cpack -G DEB && sudo dpkg -i nvim-linux64.deb
					popd
				else
          if sudo -v; then
            sudo add-apt-repository -y ppa:neovim-ppa/unstable
						sudo apt-get update
          fi
				  bootstrap_install neovim
				fi
		    ;;
    Darwin*)
		    bootstrap_install neovim --HEAD
        ;;
    *)          echo "UNKNOWN:${unameOut}"; exit 1;;
esac

nvim -V1 -v

CONFIG_DIR=${HOME}/.config
mkdir -p ${CONFIG_DIR}
rm -f ${HOME}/.config/nvim
ln -s -f $(pwd)/config ${HOME}/.config/nvim

# Language Servers


## Scheme Language Server - https://github.com/ufo5260987423/scheme-langserver


