#! /bin/bash

set -euo pipefail

cd $(dirname ${BASH_SOURCE[0]})

. ../functions.sh

export PATH="${HOME}/.local/brew/bin:${PATH}"

if ! command -v brew; then
    echo "Setting up brew"
    ../brew/setup
    echo "brew set up"
fi

brew install --HEAD terraform
terraform --version

