#! /bin/bash

set -euox pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

. ../functions.sh

if ! command -v curl >> /dev/null; then
    # NOTE: Directly call, bypassing setup to avoid accidental recursion
    # NOTE: curl is bundled with MacOS, so this only affects linux installs, so we want to avoid the recursion
    ../curl/setup curl
fi

curl -fsSL https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts | sudo tee -a /etc/hosts > /dev/null
