#! /bin/bash

set -euo pipefail

cd $(dirname ${BASH_SOURCE[0]})

. ../functions.sh

PLATFORM="$(uname -s)"
case ${PLATFORM} in
    Linux*)
        DIR=${HOME}/.config/Code/User
        ;;
    Darwin*)
        DIR="${HOME}/Library/Application Support/Code/User"
        ;;
    *)          echo "UNKNOWN:${unameOut}"; exit 1;;
esac

mkdir -p ${DIR}
SETTINGS=settings.json
KEYBINDINGS=keybindings.json
if [[ $(hostname) == *jorson* ]]; then
    SETTINGS=settings.work.json
fi
ln -s -f $(pwd)/${SETTINGS} "${DIR}/settings.json"
ln -s -f $(pwd)/${KEYBINDINGS} "${DIR}/keybindings.json"

