#! /bin/bash

set -euox pipefail

cd $(dirname ${BASH_SOURCE[0]})

. ../functions.sh

if ! command -v curl >> /dev/null; then
    # NOTE: Directly call, bypassing setup to avoid accidental recursion
    # NOTE: curl is bundled with MacOS, so this only affects linux installs, so we want to avoid the recursion
    ../curl/setup curl
fi

PLATFORM="$(uname -s)"
case ${PLATFORM} in
    Linux*)
        if sudo -v; then
            sudo dpkg-reconfigure -f noninteractive tzdata
            DEBIAN_FRONTEND=noninteractive apt-get install \
                -y \
                --no-install-recommends \
                tzdata
            bootstrap_install zsh
        fi
        ;;
    Darwin*)
            bootstrap_install zsh
        ;;
    *)          echo "UNKNOWN:${unameOut}"; exit 1;;
esac

zsh --version
export BIN_DIR="${HOME}/.local/bin"
mkdir -p ${BIN_DIR}

ZPREZTO_DIR="${HOME}/.zprezto"
if ! [[ -d ${ZPREZTO_DIR} ]]; then
    bootstrap_clone 'https://github.com/sorin-ionescu/prezto.git' ${ZPREZTO_DIR}
fi

zsh -s <<- EOF
setopt EXTENDED_GLOB
for rcfile in \${ZPREZTO_DIR}/runcoms/^README.md(.N); do
    ln -s -f "\$rcfile" "\${ZDOTDIR:-\$HOME}/.\${rcfile:t}"
done
EOF

for rcfile in "zshrc" "zpreztorc"; do
    rcfile_path="${ZDOTDIR:-$HOME}/.${rcfile}"
    rm -f ${rcfile_path}
    ln -s "$(pwd)/${rcfile}" ${rcfile_path}
done

curl -fsSL https://starship.rs/install.sh | sh -s -- --yes
