#! /bin/zsh

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${HOME}/.zprezto/init.zsh" ]]; then
  source "${HOME}/.zprezto/init.zsh"
fi

# Java classpath
export CLASSPATH=".:/usr/local/lib/antlr-4.13.1-complete.jar:${CLASSPATH}"

# PATH
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/.local/brew/bin:${PATH}"
export PATH="${HOME}/.cargo/bin:${PATH}"
export PATH="${PATH}:/Applications/Emacs.app/Contents/MacOS/bin"
export PATH="${HOME}/.local/go/bin:${PATH}"

# Guile
export GUILE_LOAD_PATH="${HOME}/.local/brew/share/guile/site/3.0"
export GUILE_LOAD_COMPILED_PATH="${HOME}/.local/brew/lib/guile/3.0/site-ccache"
export GUILE_SYSTEM_EXTENSIONS_PATH="${HOME}/.local/brew/lib/guile/3.0/extensions"

# Emacs
export LSP_USE_PLISTS=true
    
# Aliases
PLATFORM="$(uname -s)"
case ${PLATFORM} in
    Linux*)
        if command -v batcat >> /dev/null; then
            alias bat="batcat"
        fi
        ;;
    Darwin*)
        alias emacs="/Applications/Emacs.app/Contents/MacOS/Emacs"
        ;;
    *)          echo "UNKNOWN:${unameOut}"; exit 1;;
esac
alias woman="man"
alias dwr="dotnet watch run"
alias dwt="dotnet watch test"
alias sbcl="rlwrap -c sbcl"
if command -v nvim >> /dev/null; then
	alias vim=$(which nvim)
	export GIT_EDITOR=$(which nvim)
fi

# Autocompletion
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)

# NVM
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# Starship
eval "$(starship init zsh)"

eval "$(ssh-agent -s)" >> /dev/null

alias ursinia-deploy='cd ./git.sr.ht/jamesaorson/ursinia && git pull && ./deploy.bash'

