name: Mirror
on:
  push:
    branches:
      - '*' 

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: jamesaorson/composite-git-mirror@main
        with:
          target-git-url: git@git.sr.ht:~${{ github.repository }}.git
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
